CREATE DATABASE IF NOT EXISTS employeesdb;

USE employeesdb 

CREATE TABLE department{
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(30),
PRIMARY KEY (id)
}

CREATE TABLE roles{
id INT AUTO_INCREMENT NOT NULL,
title VARCHAR(30),
salary DECIMAL, 
department_id INT,
PRIMARY KEY (id)
}

CREATE TABLE employees{
id INT AUTO_INCREMENT NOT NULL,
firstname VARCHAR(),
lastname VARCHAR(),
PRIMARY KEY (id)
};
